package cli

// Property test (b) — NFR-007: a BLOCKED install leaves every target manifest
// file byte-identical (architecture §K Property row; scope spec §2.1 property
// #b; pentest cross-cuts P-8 crash-to-bypass / §C.6 fail-closed).
//
// WHY THIS IS A SECURITY PROPERTY, NOT A CONVENIENCE ONE: PenRUSH is a
// PreToolUse gate. It runs BEFORE the package manager. Its only job on a block
// is to deny — it must have ZERO side effects on the project. A gate that
// touched a lockfile or manifest on the block path would be (a) corrupting the
// user's tree on the deny path and (b) a potential write-primitive a crafted
// command could aim. The architecture's posture is that the gate reads stdin,
// queries registries, and writes ONLY under ~/.penrush/ (the audit log). This
// test proves that invariant holds across every ecosystem's block path, by
// observation rather than by reading the code: snapshot a realistic project
// tree, run the gate to a confirmed BLOCK, assert the tree is byte-identical.
//
// The property is asserted over the full set of structural-block and
// engine-block commands for all 8 ecosystems. Each case is checked for TWO
// things: (1) the verdict was actually a block (else the test is vacuous), and
// (2) every manifest byte is unchanged.

import (
	"crypto/sha256"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/penrush/penrush/internal/registry"
)

// manifestFixture is the realistic project tree a real install would mutate.
// Every common manifest/lockfile across the 8 ecosystems is present so a stray
// write anywhere is caught.
var manifestFixture = map[string]string{
	"package.json":      `{"name":"proj","version":"1.0.0","dependencies":{"left-pad":"1.3.0"}}` + "\n",
	"package-lock.json": `{"lockfileVersion":3,"packages":{}}` + "\n",
	"requirements.txt":  "requests==2.31.0\nflask==3.0.0\n",
	"pyproject.toml":    "[project]\nname = \"proj\"\nversion = \"1.0.0\"\n",
	"Cargo.toml":        "[package]\nname = \"proj\"\nversion = \"0.1.0\"\n",
	"Cargo.lock":        "# autogenerated\nversion = 3\n",
	"go.mod":            "module example.com/proj\n\ngo 1.26\n",
	"go.sum":            "",
	"Gemfile":           "source 'https://rubygems.org'\ngem 'rails'\n",
	"Gemfile.lock":      "GEM\n  remote: https://rubygems.org/\n",
	"Dockerfile":        "FROM alpine:3.19\nRUN echo hi\n",
	"sub/nested.json":   `{"x":1}` + "\n",
}

// blockingCommands across all 8 ecosystems. Each MUST resolve to a block
// (structural or engine). Engine-block cases use a "fresh" (under-cooldown) or
// erroring resolver so the gate denies.
var blockingCommands = []struct {
	eco     string
	command string
	label   string
}{
	// npm: missing exact-pin (structural) + fresh aged (engine)
	{"npm", "npm install left-pad@1.3.0", "npm missing --save-exact (structural)"},
	{"npm", "npm install --save-exact freshpkg@0.0.1", "npm fresh -> engine block"},
	// pypi: missing == pin (structural) + fresh (engine)
	{"pypi", "pip install requests", "pip missing == pin (structural)"},
	{"pypi", "pip install freshpkg==0.0.1", "pip fresh -> engine block"},
	// cargo: fresh (engine)
	{"cargo", "cargo install freshcrate", "cargo fresh -> engine block"},
	// gem: fresh (engine)
	{"gem", "gem install freshgem", "gem fresh -> engine block"},
	// go: @latest (structural) + fresh pinned (engine)
	{"go", "go install github.com/foo/bar@latest", "go @latest (structural)"},
	{"go", "go get github.com/foo/bar@v0.0.1", "go fresh -> engine block"},
	// docker: tag-only fresh (engine)
	{"docker", "docker pull alpine:edge", "docker tag-only fresh -> engine block"},
	// github: fresh repo (engine)
	{"github", "git clone https://github.com/foo/bar.git", "github fresh -> engine block"},
	// mcp: approval-gated (engine block via ErrApprovalRequired)
	{"mcp", "claude mcp add some-server", "mcp approval-gated block"},
	// system package managers (structural block, no ecosystem)
	{"", "winget install Foo.Bar", "winget (structural)"},
	{"", "brew install jq", "brew (structural)"},
}

// freshResolvers returns a resolver set where every artifact is UNDER the
// cooldown (so the age gate blocks) and mcp is approval-gated — guaranteeing a
// block verdict on every blockingCommands entry that routes through the engine.
func freshResolvers() map[string]registry.Resolver {
	fresh := fixedNow.AddDate(0, 0, -2) // 2 days old, under the 14-day default
	return map[string]registry.Resolver{
		"npm":    stubResolver{eco: "npm", published: fresh},
		"pypi":   stubResolver{eco: "pypi", published: fresh},
		"cargo":  stubResolver{eco: "cargo", published: fresh},
		"gem":    stubResolver{eco: "gem", published: fresh},
		"go":     stubResolver{eco: "go", published: fresh},
		"github": stubResolver{eco: "github", published: fresh},
		// docker tag-only resolves fresh; a digest pin would pass, but the
		// blocking case uses a tag.
		"docker": stubResolver{eco: "docker", published: fresh},
		"mcp":    parityMCP{}, // ErrApprovalRequired -> block
	}
}

func TestPropertyBlockedInstallLeavesManifestsByteIdentical(t *testing.T) {
	for _, tc := range blockingCommands {
		t.Run(tc.label, func(t *testing.T) {
			// A fresh project tree per case (so any mutation is attributable).
			proj := t.TempDir()
			writeFixture(t, proj)
			before := hashTree(t, proj)

			// A PenRUSH home OUTSIDE the project tree — the audit log writes
			// there, and the property is specifically about the PROJECT tree.
			home := initHome(t)

			decision, code, stdout, stderr := decodeHookDecision(t, home, tc.command, freshResolvers())
			action := hookDecisionToAction(decision, code)

			// (1) The verdict must actually be a block — otherwise the property
			// is vacuously satisfied and proves nothing.
			if action != "block" {
				t.Fatalf("setup error: %q did not BLOCK (got %q, decision=%q exit=%d)\nstdout:%s\nstderr:%s",
					tc.command, action, decision, code, stdout, stderr)
			}

			// (2) Every project file must be byte-identical.
			after := hashTree(t, proj)
			assertTreesEqual(t, before, after, tc.command)
		})
	}
}

// writeFixture materializes manifestFixture under root.
func writeFixture(t *testing.T, root string) {
	t.Helper()
	for rel, content := range manifestFixture {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// hashTree returns relpath -> sha256 for every regular file under root.
func hashTree(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		sum := sha256.Sum256(b)
		out[filepath.ToSlash(rel)] = string(sum[:])
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// assertTreesEqual fails with a precise diff if before != after (missing,
// added, or modified files).
func assertTreesEqual(t *testing.T, before, after map[string]string, cmd string) {
	t.Helper()
	var problems []string
	for rel, h := range before {
		ah, ok := after[rel]
		if !ok {
			problems = append(problems, "DELETED: "+rel)
			continue
		}
		if ah != h {
			problems = append(problems, "MODIFIED: "+rel)
		}
	}
	for rel := range after {
		if _, ok := before[rel]; !ok {
			problems = append(problems, "CREATED: "+rel)
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		t.Fatalf("NFR-007 VIOLATED: blocked command %q changed the project tree:\n  %s",
			cmd, strings.Join(problems, "\n  "))
	}
}
